title: <p align="center"> Vishnu Vardhan </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vishnu-vardhan-642135a8/">LinkedIn</a> |
  <a href="https://github.com/vishnu-vardhan01">GitHub</a>
 
  <br>  
  I'm working on Data Science, Artificial Intelligence & Machine Learning Business Problems.
  Worked with HSBC in the Strategy & Analytics team.
  <br>
  </p>



theme: jekyll-theme-minimal
